spring:
    datasource:
        hikari:
            driver-class-name: com.mysql.cj.jdbc.Driver
            jdbc-url: jdbc:mysql://localhost:3306/salesdb?useSSL=false&useUnicode=true&characterEncoding=utf8&serverTimezone=@time-zone@
            username: root
            password: 11111111
            maximum-pool-size: 30
            minimum-idle: 2
            max-lifetime: 180000